on:
  workflow_dispatch:

jobs:
  cbom-scan:
    runs-on: ubuntu-22.04
    name: CBOM generation
    permissions:
      contents: write
      pull-requests: write
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package -DskipTests=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create CBOM
        uses: PQCA/CBOMkit-action@v2.0.0-alpha
        id: cbom
      - name: Commit changes to new branch
        uses: actions/upload-artifact@v4
        with: 
          name: "CBOM"
          path: ${{ steps.cbom.outputs.pattern }}
          if-no-files-found: warn 

